

export default function handler(req, res) {
  const data = `One promising suggestion put forward by Selby and Clover about achieving ecological literacy is to transform schools into collaborative learning communities. A collaboration that reflects a vibrant living system that imitates the values and principles held intrinsically in natural ecosystems (Selby, 2000). Such a call is evident in the recent trends where schools are increasingly incorporating ecological themes and topics in curriculum development.

  A positive response or support is an opportunity to build a school philosophy in which environmental awareness and sensitivity are considered a priority. It is an important opportunity to give young learners, and maybe other community members who are stuck in unyielding worldviews, the chance to make the desired change. The key reason is that the collaboration will allow the integration of diverse ideas and consequently acknowledge beliefs and values held by diverse individuals.
  
  David Selby is one of the scholars who support collaborative learning or creating vibrant learning communities in schools (Selby, 2000). At this juncture, a learning community becomes more of a process than a place where academic knowledge is reinterpreted for a passing mark only. Reflecting on Mezirow’s steps of transformative learning, this process will grow systematically from “exploration of options for new roles, relationships, and actions to planning a course of action, acquiring knowledge and skills for implementing one’s plans” (Mezirow, 1999).
  
  Selby has joined Mezirow’s steps through what he calls strands. Insofar, the next strand is awakened by the achievement of the previous strand similar to Mezirow’s steps. Here, the process is clearly triggered by the new ethic in which aggressive, plundering human beings have abandoned their destructive ways, recognized their dependence on Planet Earth and attempted to live on more equal traction with the rest of nature (Selby, 2000). The chance to sustain the ecology lies in the fact that, people are presenting a deep and transformative, as in opposition to shallow and reformist ecological worldview within which the principal conjectures underlying the prevailing economic approach are nullified and changes identified.
  
  With the growing perception, it is important to develop collaborative learning with a bio-centric philosophy. The reason is that such a philosophy would embrace the idea of human versus nature in which relationship is characterized by events that are processes rather than the place where academic knowledge is reinterpreted for an economic point only. As such, environmental themes and topics that have been left out for science classes only will be solicited. Moreover, they will be balanced with other themes that leverage ecological understanding such as culture, spiritual, social and political aspects. The inclusion allows for the agreement of the diverse ideas and beliefs noted earlier.
  
  In a collaborative learning environment, the most important is the convergence of ideas and interests. Successful and sustainable school change, Fullan (Fullan,1997 as cited in Selby, 2002) suggests, “requires coherence, integration, diversity, continuous skills development, the creation of collaborative work cultures, … and a broadening of the leadership net to include as many teachers, parents, and students as possible.
  
  One promising suggestion put forward by Selby and Clover about achieving ecological literacy is to transform schools into collaborative learning communities. A collaboration that reflects a vibrant living system that imitates the values and principles held intrinsically in natural ecosystems (Selby, 2000). Such a call is evident in the recent trends where schools are increasingly incorporating ecological themes and topics in curriculum development.

  A positive response or support is an opportunity to build a school philosophy in which environmental awareness and sensitivity are considered a priority. It is an important opportunity to give young learners, and maybe other community members who are stuck in unyielding worldviews, the chance to make the desired change. The key reason is that the collaboration will allow the integration of diverse ideas and consequently acknowledge beliefs and values held by diverse individuals.
  
  David Selby is one of the scholars who support collaborative learning or creating vibrant learning communities in schools (Selby, 2000). At this juncture, a learning community becomes more of a process than a place where academic knowledge is reinterpreted for a passing mark only. Reflecting on Mezirow’s steps of transformative learning, this process will grow systematically from “exploration of options for new roles, relationships, and actions to planning a course of action, acquiring knowledge and skills for implementing one’s plans” (Mezirow, 1999).
  
  Selby has joined Mezirow’s steps through what he calls strands. Insofar, the next strand is awakened by the achievement of the previous strand similar to Mezirow’s steps. Here, the process is clearly triggered by the new ethic in which aggressive, plundering human beings have abandoned their destructive ways, recognized their dependence on Planet Earth and attempted to live on more equal traction with the rest of nature (Selby, 2000). The chance to sustain the ecology lies in the fact that, people are presenting a deep and transformative, as in opposition to shallow and reformist ecological worldview within which the principal conjectures underlying the prevailing economic approach are nullified and changes identified.
  
  With the growing perception, it is important to develop collaborative learning with a bio-centric philosophy. The reason is that such a philosophy would embrace the idea of human versus nature in which relationship is characterized by events that are processes rather than the place where academic knowledge is reinterpreted for an economic point only. As such, environmental themes and topics that have been left out for science classes only will be solicited. Moreover, they will be balanced with other themes that leverage ecological understanding such as culture, spiritual, social and political aspects. The inclusion allows for the agreement of the diverse ideas and beliefs noted earlier.
  
  In a collaborative learning environment, the most important is the convergence of ideas and interests. Successful and sustainable school change, Fullan (Fullan,1997 as cited i
    One promising suggestion put forward by Selby and Clover about achieving ecological literacy is to transform schools into collaborative learning communities. A collaboration that reflects a vibrant living system that imitates the values and principles held intrinsically in natural ecosystems (Selby, 2000). Such a call is evident in the recent trends where schools are increasingly incorporating ecological themes and topics in curriculum development.

  A positive response or support is an opportunity to build a school philosophy in which environmental awareness and sensitivity are considered a priority. It is an important opportunity to give young learners, and maybe other community members who are stuck in unyielding worldviews, the chance to make the desired change. The key reason is that the collaboration will allow the integration of diverse ideas and consequently acknowledge beliefs and values held by diverse individuals.
  
  David Selby is one of the scholars who support collaborative learning or creating vibrant learning communities in schools (Selby, 2000). At this juncture, a learning community becomes more of a process than a place where academic knowledge is reinterpreted for a passing mark only. Reflecting on Mezirow’s steps of transformative learning, this process will grow systematically from “exploration of options for new roles, relationships, and actions to planning a course of action, acquiring knowledge and skills for implementing one’s plans” (Mezirow, 1999).
  
  Selby has joined Mezirow’s steps through what he calls strands. Insofar, the next strand is awakened by the achievement of the previous strand similar to Mezirow’s steps. Here, the process is clearly triggered by the new ethic in which aggressive, plundering human beings have abandoned their destructive ways, recognized their dependence on Planet Earth and attempted to live on more equal traction with the rest of nature (Selby, 2000). The chance to sustain the ecology lies in the fact that, people are presenting a deep and transformative, as in opposition to shallow and reformist ecological worldview within which the principal conjectures underlying the prevailing economic approach are nullified and changes identified.
  
  With the growing perception, it is important to develop collaborative learning with a bio-centric philosophy. The reason is that such a philosophy would embrace the idea of human versus nature in which relationship is characterized by events that are processes rather than the place where academic knowledge is reinterpreted for an economic point only. As such, environmental themes and topics that have been left out for science classes only will be solicited. Moreover, they will be balanced with other themes that leverage ecological understanding such as culture, spiritual, social and political aspects. The inclusion allows for the agreement of the diverse ideas and beliefs noted earlier.
  
  In a collaborative learning environment, the most important is the convergence of ideas and interests. Successful and sustainable school change, Fullan (Fullan,1997 as cited i
    One promising suggestion put forward by Selby and Clover about achieving ecological literacy is to transform schools into collaborative learning communities. A collaboration that reflects a vibrant living system that imitates the values and principles held intrinsically in natural ecosystems (Selby, 2000). Such a call is evident in the recent trends where schools are increasingly incorporating ecological themes and topics in curriculum development.

  A positive response or support is an opportunity to build a school philosophy in which environmental awareness and sensitivity are considered a priority. It is an important opportunity to give young learners, and maybe other community members who are stuck in unyielding worldviews, the chance to make the desired change. The key reason is that the collaboration will allow the integration of diverse ideas and consequently acknowledge beliefs and values held by diverse individuals.
  
  David Selby is one of the scholars who support collaborative learning or creating vibrant learning communities in schools (Selby, 2000). At this juncture, a learning community becomes more of a process than a place where academic knowledge is reinterpreted for a passing mark only. Reflecting on Mezirow’s steps of transformative learning, this process will grow systematically from “exploration of options for new roles, relationships, and actions to planning a course of action, acquiring knowledge and skills for implementing one’s plans” (Mezirow, 1999).
  
  Selby has joined Mezirow’s steps through what he calls strands. Insofar, the next strand is awakened by the achievement of the previous strand similar to Mezirow’s steps. Here, the process is clearly triggered by the new ethic in which aggressive, plundering human beings have abandoned their destructive ways, recognized their dependence on Planet Earth and attempted to live on more equal traction with the rest of nature (Selby, 2000). The chance to sustain the ecology lies in the fact that, people are presenting a deep and transformative, as in opposition to shallow and reformist ecological worldview within which the principal conjectures underlying the prevailing economic approach are nullified and changes identified.
  
  With the growing perception, it is important to develop collaborative learning with a bio-centric philosophy. The reason is that such a philosophy would embrace the idea of human versus nature in which relationship is characterized by events that are processes rather than the place where academic knowledge is reinterpreted for an economic point only. As such, environmental themes and topics that have been left out for science classes only will be solicited. Moreover, they will be balanced with other themes that leverage ecological understanding such as culture, spiritual, social and political aspects. The inclusion allows for the agreement of the diverse ideas and beliefs noted earlier.
  
  In a collaborative learning environment, the most important is the convergence of ideas and interests. Successful and sustainable school change, Fullan (Fullan,1997 as cited i
    
    One promising suggestion put forward by Selby and Clover about achieving ecological literacy is to transform schools into collaborative learning communities. A collaboration that reflects a vibrant living system that imitates the values and principles held intrinsically in natural ecosystems (Selby, 2000). Such a call is evident in the recent trends where schools are increasingly incorporating ecological themes and topics in curriculum development.

  A positive response or support is an opportunity to build a school philosophy in which environmental awareness and sensitivity are considered a priority. It is an important opportunity to give young learners, and maybe other community members who are stuck in unyielding worldviews, the chance to make the desired change. The key reason is that the collaboration will allow the integration of diverse ideas and consequently acknowledge beliefs and values held by diverse individuals.
  
  David Selby is one of the scholars who support collaborative learning or creating vibrant learning communities in schools (Selby, 2000). At this juncture, a learning community becomes more of a process than a place where academic knowledge is reinterpreted for a passing mark only. Reflecting on Mezirow’s steps of transformative learning, this process will grow systematically from “exploration of options for new roles, relationships, and actions to planning a course of action, acquiring knowledge and skills for implementing one’s plans” (Mezirow, 1999).
  
  Selby has joined Mezirow’s steps through what he calls strands. Insofar, the next strand is awakened by the achievement of the previous strand similar to Mezirow’s steps. Here, the process is clearly triggered by the new ethic in which aggressive, plundering human beings have abandoned their destructive ways, recognized their dependence on Planet Earth and attempted to live on more equal traction with the rest of nature (Selby, 2000). The chance to sustain the ecology lies in the fact that, people are presenting a deep and transformative, as in opposition to shallow and reformist ecological worldview within which the principal conjectures underlying the prevailing economic approach are nullified and changes identified.
  
  With the growing perception, it is important to develop collaborative learning with a bio-centric philosophy. The reason is that such a philosophy would embrace the idea of human versus nature in which relationship is characterized by events that are processes rather than the place where academic knowledge is reinterpreted for an economic point only. As such, environmental themes and topics that have been left out for science classes only will be solicited. Moreover, they will be balanced with other themes that leverage ecological understanding such as culture, spiritual, social and political aspects. The inclusion allows for the agreement of the diverse ideas and beliefs noted earlier.
  
  In a collaborative learning environment, the most important is the convergence of ideas and interests. Successful and sustainable school change, Fullan (Fullan,1997 as cited i
    
    
    
    One promising suggestion put forward by Selby and Clover about achieving ecological literacy is to transform schools into collaborative learning communities. A collaboration that reflects a vibrant living system that imitates the values and principles held intrinsically in natural ecosystems (Selby, 2000). Such a call is evident in the recent trends where schools are increasingly incorporating ecological themes and topics in curriculum development.

  A positive response or support is an opportunity to build a school philosophy in which environmental awareness and sensitivity are considered a priority. It is an important opportunity to give young learners, and maybe other community members who are stuck in unyielding worldviews, the chance to make the desired change. The key reason is that the collaboration will allow the integration of diverse ideas and consequently acknowledge beliefs and values held by diverse individuals.
  
  David Selby is one of the scholars who support collaborative learning or creating vibrant learning communities in schools (Selby, 2000). At this juncture, a learning community becomes more of a process than a place where academic knowledge is reinterpreted for a passing mark only. Reflecting on Mezirow’s steps of transformative learning, this process will grow systematically from “exploration of options for new roles, relationships, and actions to planning a course of action, acquiring knowledge and skills for implementing one’s plans” (Mezirow, 1999).
  
  Selby has joined Mezirow’s steps through what he calls strands. Insofar, the next strand is awakened by the achievement of the previous strand similar to Mezirow’s steps. Here, the process is clearly triggered by the new ethic in which aggressive, plundering human beings have abandoned their destructive ways, recognized their dependence on Planet Earth and attempted to live on more equal traction with the rest of nature (Selby, 2000). The chance to sustain the ecology lies in the fact that, people are presenting a deep and transformative, as in opposition to shallow and reformist ecological worldview within which the principal conjectures underlying the prevailing economic approach are nullified and changes identified.
  
  With the growing perception, it is important to develop collaborative learning with a bio-centric philosophy. The reason is that such a philosophy would embrace the idea of human versus nature in which relationship is characterized by events that are processes rather than the place where academic knowledge is reinterpreted for an economic point only. As such, environmental themes and topics that have been left out for science classes only will be solicited. Moreover, they will be balanced with other themes that leverage ecological understanding such as culture, spiritual, social and political aspects. The inclusion allows for the agreement of the diverse ideas and beliefs noted earlier.
  
  In a collaborative learning environment, the most important is the convergence of ideas and interests. Successful and sustainable school change, Fullan (Fullan,1997 as cited i
    
    
    
    
    One promising suggestion put forward by Selby and Clover about achieving ecological literacy is to transform schools into collaborative learning communities. A collaboration that reflects a vibrant living system that imitates the values and principles held intrinsically in natural ecosystems (Selby, 2000). Such a call is evident in the recent trends where schools are increasingly incorporating ecological themes and topics in curriculum development.

  A positive response or support is an opportunity to build a school philosophy in which environmental awareness and sensitivity are considered a priority. It is an important opportunity to give young learners, and maybe other community members who are stuck in unyielding worldviews, the chance to make the desired change. The key reason is that the collaboration will allow the integration of diverse ideas and consequently acknowledge beliefs and values held by diverse individuals.
  
  David Selby is one of the scholars who support collaborative learning or creating vibrant learning communities in schools (Selby, 2000). At this juncture, a learning community becomes more of a process than a place where academic knowledge is reinterpreted for a passing mark only. Reflecting on Mezirow’s steps of transformative learning, this process will grow systematically from “exploration of options for new roles, relationships, and actions to planning a course of action, acquiring knowledge and skills for implementing one’s plans” (Mezirow, 1999).
  
  Selby has joined Mezirow’s steps through what he calls strands. Insofar, the next strand is awakened by the achievement of the previous strand similar to Mezirow’s steps. Here, the process is clearly triggered by the new ethic in which aggressive, plundering human beings have abandoned their destructive ways, recognized their dependence on Planet Earth and attempted to live on more equal traction with the rest of nature (Selby, 2000). The chance to sustain the ecology lies in the fact that, people are presenting a deep and transformative, as in opposition to shallow and reformist ecological worldview within which the principal conjectures underlying the prevailing economic approach are nullified and changes identified.
  
  With the growing perception, it is important to develop collaborative learning with a bio-centric philosophy. The reason is that such a philosophy would embrace the idea of human versus nature in which relationship is characterized by events that are processes rather than the place where academic knowledge is reinterpreted for an economic point only. As such, environmental themes and topics that have been left out for science classes only will be solicited. Moreover, they will be balanced with other themes that leverage ecological understanding such as culture, spiritual, social and political aspects. The inclusion allows for the agreement of the diverse ideas and beliefs noted earlier.
  
  In a collaborative learning environment, the most important is the convergence of ideas and interests. Successful and sustainable school change, Fullan (Fullan,1997 as cited i
    
    
    One promising suggestion put forward by Selby and Clover about achieving ecological literacy is to transform schools into collaborative learning communities. A collaboration that reflects a vibrant living system that imitates the values and principles held intrinsically in natural ecosystems (Selby, 2000). Such a call is evident in the recent trends where schools are increasingly incorporating ecological themes and topics in curriculum development.

  A positive response or support is an opportunity to build a school philosophy in which environmental awareness and sensitivity are considered a priority. It is an important opportunity to give young learners, and maybe other community members who are stuck in unyielding worldviews, the chance to make the desired change. The key reason is that the collaboration will allow the integration of diverse ideas and consequently acknowledge beliefs and values held by diverse individuals.
  
  David Selby is one of the scholars who support collaborative learning or creating vibrant learning communities in schools (Selby, 2000). At this juncture, a learning community becomes more of a process than a place where academic knowledge is reinterpreted for a passing mark only. Reflecting on Mezirow’s steps of transformative learning, this process will grow systematically from “exploration of options for new roles, relationships, and actions to planning a course of action, acquiring knowledge and skills for implementing one’s plans” (Mezirow, 1999).
  
  Selby has joined Mezirow’s steps through what he calls strands. Insofar, the next strand is awakened by the achievement of the previous strand similar to Mezirow’s steps. Here, the process is clearly triggered by the new ethic in which aggressive, plundering human beings have abandoned their destructive ways, recognized their dependence on Planet Earth and attempted to live on more equal traction with the rest of nature (Selby, 2000). The chance to sustain the ecology lies in the fact that, people are presenting a deep and transformative, as in opposition to shallow and reformist ecological worldview within which the principal conjectures underlying the prevailing economic approach are nullified and changes identified.
  
  With the growing perception, it is important to develop collaborative learning with a bio-centric philosophy. The reason is that such a philosophy would embrace the idea of human versus nature in which relationship is characterized by events that are processes rather than the place where academic knowledge is reinterpreted for an economic point only. As such, environmental themes and topics that have been left out for science classes only will be solicited. Moreover, they will be balanced with other themes that leverage ecological understanding such as culture, spiritual, social and political aspects. The inclusion allows for the agreement of the diverse ideas and beliefs noted earlier.
  
  In a collaborative learning environment, the most important is the convergence of ideas and interests. Successful and sustainable school change, Fullan (Fullan,1997 as cited i
    
    One promising suggestion put forward by Selby and Clover about achieving ecological literacy is to transform schools into collaborative learning communities. A collaboration that reflects a vibrant living system that imitates the values and principles held intrinsically in natural ecosystems (Selby, 2000). Such a call is evident in the recent trends where schools are increasingly incorporating ecological themes and topics in curriculum development.

  A positive response or support is an opportunity to build a school philosophy in which environmental awareness and sensitivity are considered a priority. It is an important opportunity to give young learners, and maybe other community members who are stuck in unyielding worldviews, the chance to make the desired change. The key reason is that the collaboration will allow the integration of diverse ideas and consequently acknowledge beliefs and values held by diverse individuals.
  
  David Selby is one of the scholars who support collaborative learning or creating vibrant learning communities in schools (Selby, 2000). At this juncture, a learning community becomes more of a process than a place where academic knowledge is reinterpreted for a passing mark only. Reflecting on Mezirow’s steps of transformative learning, this process will grow systematically from “exploration of options for new roles, relationships, and actions to planning a course of action, acquiring knowledge and skills for implementing one’s plans” (Mezirow, 1999).
  
  Selby has joined Mezirow’s steps through what he calls strands. Insofar, the next strand is awakened by the achievement of the previous strand similar to Mezirow’s steps. Here, the process is clearly triggered by the new ethic in which aggressive, plundering human beings have abandoned their destructive ways, recognized their dependence on Planet Earth and attempted to live on more equal traction with the rest of nature (Selby, 2000). The chance to sustain the ecology lies in the fact that, people are presenting a deep and transformative, as in opposition to shallow and reformist ecological worldview within which the principal conjectures underlying the prevailing economic approach are nullified and changes identified.
  
  With the growing perception, it is important to develop collaborative learning with a bio-centric philosophy. The reason is that such a philosophy would embrace the idea of human versus nature in which relationship is characterized by events that are processes rather than the place where academic knowledge is reinterpreted for an economic point only. As such, environmental themes and topics that have been left out for science classes only will be solicited. Moreover, they will be balanced with other themes that leverage ecological understanding such as culture, spiritual, social and political aspects. The inclusion allows for the agreement of the diverse ideas and beliefs noted earlier.
  
  In a collaborative learning environment, the most important is the convergence of ideas and interests. Successful and sustainable school change, Fullan (Fullan,1997 as cited i
    One promising suggestion put forward by Selby and Clover about achieving ecological literacy is to transform schools into collaborative learning communities. A collaboration that reflects a vibrant living system that imitates the values and principles held intrinsically in natural ecosystems (Selby, 2000). Such a call is evident in the recent trends where schools are increasingly incorporating ecological themes and topics in curriculum development.

  A positive response or support is an opportunity to build a school philosophy in which environmental awareness and sensitivity are considered a priority. It is an important opportunity to give young learners, and maybe other community members who are stuck in unyielding worldviews, the chance to make the desired change. The key reason is that the collaboration will allow the integration of diverse ideas and consequently acknowledge beliefs and values held by diverse individuals.
  
  David Selby is one of the scholars who support collaborative learning or creating vibrant learning communities in schools (Selby, 2000). At this juncture, a learning community becomes more of a process than a place where academic knowledge is reinterpreted for a passing mark only. Reflecting on Mezirow’s steps of transformative learning, this process will grow systematically from “exploration of options for new roles, relationships, and actions to planning a course of action, acquiring knowledge and skills for implementing one’s plans” (Mezirow, 1999).
  
  Selby has joined Mezirow’s steps through what he calls strands. Insofar, the next strand is awakened by the achievement of the previous strand similar to Mezirow’s steps. Here, the process is clearly triggered by the new ethic in which aggressive, plundering human beings have abandoned their destructive ways, recognized their dependence on Planet Earth and attempted to live on more equal traction with the rest of nature (Selby, 2000). The chance to sustain the ecology lies in the fact that, people are presenting a deep and transformative, as in opposition to shallow and reformist ecological worldview within which the principal conjectures underlying the prevailing economic approach are nullified and changes identified.
  
  With the growing perception, it is important to develop collaborative learning with a bio-centric philosophy. The reason is that such a philosophy would embrace the idea of human versus nature in which relationship is characterized by events that are processes rather than the place where academic knowledge is reinterpreted for an economic point only. As such, environmental themes and topics that have been left out for science classes only will be solicited. Moreover, they will be balanced with other themes that leverage ecological understanding such as culture, spiritual, social and political aspects. The inclusion allows for the agreement of the diverse ideas and beliefs noted earlier.
  
  In a collaborative learning environment, the most important is the convergence of ideas and interests. Successful and sustainable school change, Fullan (Fullan,1997 as cited i
    
    One promising suggestion put forward by Selby and Clover about achieving ecological literacy is to transform schools into collaborative learning communities. A collaboration that reflects a vibrant living system that imitates the values and principles held intrinsically in natural ecosystems (Selby, 2000). Such a call is evident in the recent trends where schools are increasingly incorporating ecological themes and topics in curriculum development.

  A positive response or support is an opportunity to build a school philosophy in which environmental awareness and sensitivity are considered a priority. It is an important opportunity to give young learners, and maybe other community members who are stuck in unyielding worldviews, the chance to make the desired change. The key reason is that the collaboration will allow the integration of diverse ideas and consequently acknowledge beliefs and values held by diverse individuals.
  
  David Selby is one of the scholars who support collaborative learning or creating vibrant learning communities in schools (Selby, 2000). At this juncture, a learning community becomes more of a process than a place where academic knowledge is reinterpreted for a passing mark only. Reflecting on Mezirow’s steps of transformative learning, this process will grow systematically from “exploration of options for new roles, relationships, and actions to planning a course of action, acquiring knowledge and skills for implementing one’s plans” (Mezirow, 1999).
  
  Selby has joined Mezirow’s steps through what he calls strands. Insofar, the next strand is awakened by the achievement of the previous strand similar to Mezirow’s steps. Here, the process is clearly triggered by the new ethic in which aggressive, plundering human beings have abandoned their destructive ways, recognized their dependence on Planet Earth and attempted to live on more equal traction with the rest of nature (Selby, 2000). The chance to sustain the ecology lies in the fact that, people are presenting a deep and transformative, as in opposition to shallow and reformist ecological worldview within which the principal conjectures underlying the prevailing economic approach are nullified and changes identified.
  
  With the growing perception, it is important to develop collaborative learning with a bio-centric philosophy. The reason is that such a philosophy would embrace the idea of human versus nature in which relationship is characterized by events that are processes rather than the place where academic knowledge is reinterpreted for an economic point only. As such, environmental themes and topics that have been left out for science classes only will be solicited. Moreover, they will be balanced with other themes that leverage ecological understanding such as culture, spiritual, social and political aspects. The inclusion allows for the agreement of the diverse ideas and beliefs noted earlier.
  
  In a collaborative learning environment, the most important is the convergence of ideas and interests. Successful and sustainable school change, Fullan (Fullan,1997 as cited i
    
    
    One promising suggestion put forward by Selby and Clover about achieving ecological literacy is to transform schools into collaborative learning communities. A collaboration that reflects a vibrant living system that imitates the values and principles held intrinsically in natural ecosystems (Selby, 2000). Such a call is evident in the recent trends where schools are increasingly incorporating ecological themes and topics in curriculum development.

  A positive response or support is an opportunity to build a school philosophy in which environmental awareness and sensitivity are considered a priority. It is an important opportunity to give young learners, and maybe other community members who are stuck in unyielding worldviews, the chance to make the desired change. The key reason is that the collaboration will allow the integration of diverse ideas and consequently acknowledge beliefs and values held by diverse individuals.
  
  David Selby is one of the scholars who support collaborative learning or creating vibrant learning communities in schools (Selby, 2000). At this juncture, a learning community becomes more of a process than a place where academic knowledge is reinterpreted for a passing mark only. Reflecting on Mezirow’s steps of transformative learning, this process will grow systematically from “exploration of options for new roles, relationships, and actions to planning a course of action, acquiring knowledge and skills for implementing one’s plans” (Mezirow, 1999).
  
  Selby has joined Mezirow’s steps through what he calls strands. Insofar, the next strand is awakened by the achievement of the previous strand similar to Mezirow’s steps. Here, the process is clearly triggered by the new ethic in which aggressive, plundering human beings have abandoned their destructive ways, recognized their dependence on Planet Earth and attempted to live on more equal traction with the rest of nature (Selby, 2000). The chance to sustain the ecology lies in the fact that, people are presenting a deep and transformative, as in opposition to shallow and reformist ecological worldview within which the principal conjectures underlying the prevailing economic approach are nullified and changes identified.
  
  With the growing perception, it is important to develop collaborative learning with a bio-centric philosophy. The reason is that such a philosophy would embrace the idea of human versus nature in which relationship is characterized by events that are processes rather than the place where academic knowledge is reinterpreted for an economic point only. As such, environmental themes and topics that have been left out for science classes only will be solicited. Moreover, they will be balanced with other themes that leverage ecological understanding such as culture, spiritual, social and political aspects. The inclusion allows for the agreement of the diverse ideas and beliefs noted earlier.
  
  In a collaborative learning environment, the most important is the convergence of ideas and interests. Successful and sustainable school change, Fullan (Fullan,1997 as cited i
    One promising suggestion put forward by Selby and Clover about achieving ecological literacy is to transform schools into collaborative learning communities. A collaboration that reflects a vibrant living system that imitates the values and principles held intrinsically in natural ecosystems (Selby, 2000). Such a call is evident in the recent trends where schools are increasingly incorporating ecological themes and topics in curriculum development.

  A positive response or support is an opportunity to build a school philosophy in which environmental awareness and sensitivity are considered a priority. It is an important opportunity to give young learners, and maybe other community members who are stuck in unyielding worldviews, the chance to make the desired change. The key reason is that the collaboration will allow the integration of diverse ideas and consequently acknowledge beliefs and values held by diverse individuals.
  
  David Selby is one of the scholars who support collaborative learning or creating vibrant learning communities in schools (Selby, 2000). At this juncture, a learning community becomes more of a process than a place where academic knowledge is reinterpreted for a passing mark only. Reflecting on Mezirow’s steps of transformative learning, this process will grow systematically from “exploration of options for new roles, relationships, and actions to planning a course of action, acquiring knowledge and skills for implementing one’s plans” (Mezirow, 1999).
  
  Selby has joined Mezirow’s steps through what he calls strands. Insofar, the next strand is awakened by the achievement of the previous strand similar to Mezirow’s steps. Here, the process is clearly triggered by the new ethic in which aggressive, plundering human beings have abandoned their destructive ways, recognized their dependence on Planet Earth and attempted to live on more equal traction with the rest of nature (Selby, 2000). The chance to sustain the ecology lies in the fact that, people are presenting a deep and transformative, as in opposition to shallow and reformist ecological worldview within which the principal conjectures underlying the prevailing economic approach are nullified and changes identified.
  
  With the growing perception, it is important to develop collaborative learning with a bio-centric philosophy. The reason is that such a philosophy would embrace the idea of human versus nature in which relationship is characterized by events that are processes rather than the place where academic knowledge is reinterpreted for an economic point only. As such, environmental themes and topics that have been left out for science classes only will be solicited. Moreover, they will be balanced with other themes that leverage ecological understanding such as culture, spiritual, social and political aspects. The inclusion allows for the agreement of the diverse ideas and beliefs noted earlier.
  
  In a collaborative learning environment, the most important is the convergence of ideas and interests. Successful and sustainable school change, Fullan (Fullan,1997 as cited i
    
    One promising suggestion put forward by Selby and Clover about achieving ecological literacy is to transform schools into collaborative learning communities. A collaboration that reflects a vibrant living system that imitates the values and principles held intrinsically in natural ecosystems (Selby, 2000). Such a call is evident in the recent trends where schools are increasingly incorporating ecological themes and topics in curriculum development.

  A positive response or support is an opportunity to build a school philosophy in which environmental awareness and sensitivity are considered a priority. It is an important opportunity to give young learners, and maybe other community members who are stuck in unyielding worldviews, the chance to make the desired change. The key reason is that the collaboration will allow the integration of diverse ideas and consequently acknowledge beliefs and values held by diverse individuals.
  
  David Selby is one of the scholars who support collaborative learning or creating vibrant learning communities in schools (Selby, 2000). At this juncture, a learning community becomes more of a process than a place where academic knowledge is reinterpreted for a passing mark only. Reflecting on Mezirow’s steps of transformative learning, this process will grow systematically from “exploration of options for new roles, relationships, and actions to planning a course of action, acquiring knowledge and skills for implementing one’s plans” (Mezirow, 1999).
  
  Selby has joined Mezirow’s steps through what he calls strands. Insofar, the next strand is awakened by the achievement of the previous strand similar to Mezirow’s steps. Here, the process is clearly triggered by the new ethic in which aggressive, plundering human beings have abandoned their destructive ways, recognized their dependence on Planet Earth and attempted to live on more equal traction with the rest of nature (Selby, 2000). The chance to sustain the ecology lies in the fact that, people are presenting a deep and transformative, as in opposition to shallow and reformist ecological worldview within which the principal conjectures underlying the prevailing economic approach are nullified and changes identified.
  
  With the growing perception, it is important to develop collaborative learning with a bio-centric philosophy. The reason is that such a philosophy would embrace the idea of human versus nature in which relationship is characterized by events that are processes rather than the place where academic knowledge is reinterpreted for an economic point only. As such, environmental themes and topics that have been left out for science classes only will be solicited. Moreover, they will be balanced with other themes that leverage ecological understanding such as culture, spiritual, social and political aspects. The inclusion allows for the agreement of the diverse ideas and beliefs noted earlier.
  
  In a collaborative learning environment, the most important is the convergence of ideas and interests. Successful and sustainable school change, Fullan (Fullan,1997 as cited i
    One promising suggestion put forward by Selby and Clover about achieving ecological literacy is to transform schools into collaborative learning communities. A collaboration that reflects a vibrant living system that imitates the values and principles held intrinsically in natural ecosystems (Selby, 2000). Such a call is evident in the recent trends where schools are increasingly incorporating ecological themes and topics in curriculum development.

  A positive response or support is an opportunity to build a school philosophy in which environmental awareness and sensitivity are considered a priority. It is an important opportunity to give young learners, and maybe other community members who are stuck in unyielding worldviews, the chance to make the desired change. The key reason is that the collaboration will allow the integration of diverse ideas and consequently acknowledge beliefs and values held by diverse individuals.
  
  David Selby is one of the scholars who support collaborative learning or creating vibrant learning communities in schools (Selby, 2000). At this juncture, a learning community becomes more of a process than a place where academic knowledge is reinterpreted for a passing mark only. Reflecting on Mezirow’s steps of transformative learning, this process will grow systematically from “exploration of options for new roles, relationships, and actions to planning a course of action, acquiring knowledge and skills for implementing one’s plans” (Mezirow, 1999).
  
  Selby has joined Mezirow’s steps through what he calls strands. Insofar, the next strand is awakened by the achievement of the previous strand similar to Mezirow’s steps. Here, the process is clearly triggered by the new ethic in which aggressive, plundering human beings have abandoned their destructive ways, recognized their dependence on Planet Earth and attempted to live on more equal traction with the rest of nature (Selby, 2000). The chance to sustain the ecology lies in the fact that, people are presenting a deep and transformative, as in opposition to shallow and reformist ecological worldview within which the principal conjectures underlying the prevailing economic approach are nullified and changes identified.
  
  With the growing perception, it is important to develop collaborative learning with a bio-centric philosophy. The reason is that such a philosophy would embrace the idea of human versus nature in which relationship is characterized by events that are processes rather than the place where academic knowledge is reinterpreted for an economic point only. As such, environmental themes and topics that have been left out for science classes only will be solicited. Moreover, they will be balanced with other themes that leverage ecological understanding such as culture, spiritual, social and political aspects. The inclusion allows for the agreement of the diverse ideas and beliefs noted earlier.
  
  In a collaborative learning environment, the most important is the convergence of ideas and interests. Successful and sustainable school change, Fullan (Fullan,1997 as cited in Selby, 2002) suggests, “requires coherence, integration, diversity, continuous skills development, the creation of collaborative work cultures, … and a broadening of the leadership net to include as many teachers, parents, and students as possible.
  
  One promising suggestion put forward by Selby and Clover about achieving ecological literacy is to transform schools into collaborative learning communities. A collaboration that reflects a vibrant living system that imitates the values and principles held intrinsically in natural ecosystems (Selby, 2000). Such a call is evident in the recent trends where schools are increasingly incorporating ecological themes and topics in curriculum development.

  A positive response or support is an opportunity to build a school philosophy in which environmental awareness and sensitivity are considered a priority. It is an important opportunity to give young learners, and maybe other community members who are stuck in unyielding worldviews, the chance to make the desired change. The key reason is that the collaboration will allow the integration of diverse ideas and consequently acknowledge beliefs and values held by diverse individuals.
  
  David Selby is one of the scholars who support collaborative learning or creating vibrant learning communities in schools (Selby, 2000). At this juncture, a learning community becomes more of a process than a place where academic knowledge is reinterpreted for a passing mark only. Reflecting on Mezirow’s steps of transformative learning, this process will grow systematically from “exploration of options for new roles, relationships, and actions to planning a course of action, acquiring knowledge and skills for implementing one’s plans” (Mezirow, 1999).
  
  Selby has joined Mezirow’s steps through what he calls strands. Insofar, the next strand is awakened by the achievement of the previous strand similar to Mezirow’s steps. Here, the process is clearly triggered by the new ethic in which aggressive, plundering human beings have abandoned their destructive ways, recognized their dependence on Planet Earth and attempted to live on more equal traction with the rest of nature (Selby, 2000). The chance to sustain the ecology lies in the fact that, people are presenting a deep and transformative, as in opposition to shallow and reformist ecological worldview within which the principal conjectures underlying the prevailing economic approach are nullified and changes identified.
  
  With the growing perception, it is important to develop collaborative learning with a bio-centric philosophy. The reason is that such a philosophy would embrace the idea of human versus nature in which relationship is characterized by events that are processes rather than the place where academic knowledge is reinterpreted for an economic point only. As such, environmental themes and topics that have been left out for science classes only will be solicited. Moreover, they will be balanced with other themes that leverage ecological understanding such as culture, spiritual, social and political aspects. The inclusion allows for the agreement of the diverse ideas and beliefs noted earlier.
  
  In a collaborative learning environment, the most important is the convergence of ideas and interests. Successful and sustainable school change, Fullan (Fullan,1997 as cited i
    One promising suggestion put forward by Selby and Clover about achieving ecological literacy is to transform schools into collaborative learning communities. A collaboration that reflects a vibrant living system that imitates the values and principles held intrinsically in natural ecosystems (Selby, 2000). Such a call is evident in the recent trends where schools are increasingly incorporating ecological themes and topics in curriculum development.

  A positive response or support is an opportunity to build a school philosophy in which environmental awareness and sensitivity are considered a priority. It is an important opportunity to give young learners, and maybe other community members who are stuck in unyielding worldviews, the chance to make the desired change. The key reason is that the collaboration will allow the integration of diverse ideas and consequently acknowledge beliefs and values held by diverse individuals.
  
  David Selby is one of the scholars who support collaborative learning or creating vibrant learning communities in schools (Selby, 2000). At this juncture, a learning community becomes more of a process than a place where academic knowledge is reinterpreted for a passing mark only. Reflecting on Mezirow’s steps of transformative learning, this process will grow systematically from “exploration of options for new roles, relationships, and actions to planning a course of action, acquiring knowledge and skills for implementing one’s plans” (Mezirow, 1999).
  
  Selby has joined Mezirow’s steps through what he calls strands. Insofar, the next strand is awakened by the achievement of the previous strand similar to Mezirow’s steps. Here, the process is clearly triggered by the new ethic in which aggressive, plundering human beings have abandoned their destructive ways, recognized their dependence on Planet Earth and attempted to live on more equal traction with the rest of nature (Selby, 2000). The chance to sustain the ecology lies in the fact that, people are presenting a deep and transformative, as in opposition to shallow and reformist ecological worldview within which the principal conjectures underlying the prevailing economic approach are nullified and changes identified.
  
  With the growing perception, it is important to develop collaborative learning with a bio-centric philosophy. The reason is that such a philosophy would embrace the idea of human versus nature in which relationship is characterized by events that are processes rather than the place where academic knowledge is reinterpreted for an economic point only. As such, environmental themes and topics that have been left out for science classes only will be solicited. Moreover, they will be balanced with other themes that leverage ecological understanding such as culture, spiritual, social and political aspects. The inclusion allows for the agreement of the diverse ideas and beliefs noted earlier.
  
  In a collaborative learning environment, the most important is the convergence of ideas and interests. Successful and sustainable school change, Fullan (Fullan,1997 as cited i
    One promising suggestion put forward by Selby and Clover about achieving ecological literacy is to transform schools into collaborative learning communities. A collaboration that reflects a vibrant living system that imitates the values and principles held intrinsically in natural ecosystems (Selby, 2000). Such a call is evident in the recent trends where schools are increasingly incorporating ecological themes and topics in curriculum development.

  A positive response or support is an opportunity to build a school philosophy in which environmental awareness and sensitivity are considered a priority. It is an important opportunity to give young learners, and maybe other community members who are stuck in unyielding worldviews, the chance to make the desired change. The key reason is that the collaboration will allow the integration of diverse ideas and consequently acknowledge beliefs and values held by diverse individuals.
  
  David Selby is one of the scholars who support collaborative learning or creating vibrant learning communities in schools (Selby, 2000). At this juncture, a learning community becomes more of a process than a place where academic knowledge is reinterpreted for a passing mark only. Reflecting on Mezirow’s steps of transformative learning, this process will grow systematically from “exploration of options for new roles, relationships, and actions to planning a course of action, acquiring knowledge and skills for implementing one’s plans” (Mezirow, 1999).
  
  Selby has joined Mezirow’s steps through what he calls strands. Insofar, the next strand is awakened by the achievement of the previous strand similar to Mezirow’s steps. Here, the process is clearly triggered by the new ethic in which aggressive, plundering human beings have abandoned their destructive ways, recognized their dependence on Planet Earth and attempted to live on more equal traction with the rest of nature (Selby, 2000). The chance to sustain the ecology lies in the fact that, people are presenting a deep and transformative, as in opposition to shallow and reformist ecological worldview within which the principal conjectures underlying the prevailing economic approach are nullified and changes identified.
  
  With the growing perception, it is important to develop collaborative learning with a bio-centric philosophy. The reason is that such a philosophy would embrace the idea of human versus nature in which relationship is characterized by events that are processes rather than the place where academic knowledge is reinterpreted for an economic point only. As such, environmental themes and topics that have been left out for science classes only will be solicited. Moreover, they will be balanced with other themes that leverage ecological understanding such as culture, spiritual, social and political aspects. The inclusion allows for the agreement of the diverse ideas and beliefs noted earlier.
  
  In a collaborative learning environment, the most important is the convergence of ideas and interests. Successful and sustainable school change, Fullan (Fullan,1997 as cited i
    
    One promising suggestion put forward by Selby and Clover about achieving ecological literacy is to transform schools into collaborative learning communities. A collaboration that reflects a vibrant living system that imitates the values and principles held intrinsically in natural ecosystems (Selby, 2000). Such a call is evident in the recent trends where schools are increasingly incorporating ecological themes and topics in curriculum development.

  A positive response or support is an opportunity to build a school philosophy in which environmental awareness and sensitivity are considered a priority. It is an important opportunity to give young learners, and maybe other community members who are stuck in unyielding worldviews, the chance to make the desired change. The key reason is that the collaboration will allow the integration of diverse ideas and consequently acknowledge beliefs and values held by diverse individuals.
  
  David Selby is one of the scholars who support collaborative learning or creating vibrant learning communities in schools (Selby, 2000). At this juncture, a learning community becomes more of a process than a place where academic knowledge is reinterpreted for a passing mark only. Reflecting on Mezirow’s steps of transformative learning, this process will grow systematically from “exploration of options for new roles, relationships, and actions to planning a course of action, acquiring knowledge and skills for implementing one’s plans” (Mezirow, 1999).
  
  Selby has joined Mezirow’s steps through what he calls strands. Insofar, the next strand is awakened by the achievement of the previous strand similar to Mezirow’s steps. Here, the process is clearly triggered by the new ethic in which aggressive, plundering human beings have abandoned their destructive ways, recognized their dependence on Planet Earth and attempted to live on more equal traction with the rest of nature (Selby, 2000). The chance to sustain the ecology lies in the fact that, people are presenting a deep and transformative, as in opposition to shallow and reformist ecological worldview within which the principal conjectures underlying the prevailing economic approach are nullified and changes identified.
  
  With the growing perception, it is important to develop collaborative learning with a bio-centric philosophy. The reason is that such a philosophy would embrace the idea of human versus nature in which relationship is characterized by events that are processes rather than the place where academic knowledge is reinterpreted for an economic point only. As such, environmental themes and topics that have been left out for science classes only will be solicited. Moreover, they will be balanced with other themes that leverage ecological understanding such as culture, spiritual, social and political aspects. The inclusion allows for the agreement of the diverse ideas and beliefs noted earlier.
  
  In a collaborative learning environment, the most important is the convergence of ideas and interests. Successful and sustainable school change, Fullan (Fullan,1997 as cited i
    
    
    
    One promising suggestion put forward by Selby and Clover about achieving ecological literacy is to transform schools into collaborative learning communities. A collaboration that reflects a vibrant living system that imitates the values and principles held intrinsically in natural ecosystems (Selby, 2000). Such a call is evident in the recent trends where schools are increasingly incorporating ecological themes and topics in curriculum development.

  A positive response or support is an opportunity to build a school philosophy in which environmental awareness and sensitivity are considered a priority. It is an important opportunity to give young learners, and maybe other community members who are stuck in unyielding worldviews, the chance to make the desired change. The key reason is that the collaboration will allow the integration of diverse ideas and consequently acknowledge beliefs and values held by diverse individuals.
  
  David Selby is one of the scholars who support collaborative learning or creating vibrant learning communities in schools (Selby, 2000). At this juncture, a learning community becomes more of a process than a place where academic knowledge is reinterpreted for a passing mark only. Reflecting on Mezirow’s steps of transformative learning, this process will grow systematically from “exploration of options for new roles, relationships, and actions to planning a course of action, acquiring knowledge and skills for implementing one’s plans” (Mezirow, 1999).
  
  Selby has joined Mezirow’s steps through what he calls strands. Insofar, the next strand is awakened by the achievement of the previous strand similar to Mezirow’s steps. Here, the process is clearly triggered by the new ethic in which aggressive, plundering human beings have abandoned their destructive ways, recognized their dependence on Planet Earth and attempted to live on more equal traction with the rest of nature (Selby, 2000). The chance to sustain the ecology lies in the fact that, people are presenting a deep and transformative, as in opposition to shallow and reformist ecological worldview within which the principal conjectures underlying the prevailing economic approach are nullified and changes identified.
  
  With the growing perception, it is important to develop collaborative learning with a bio-centric philosophy. The reason is that such a philosophy would embrace the idea of human versus nature in which relationship is characterized by events that are processes rather than the place where academic knowledge is reinterpreted for an economic point only. As such, environmental themes and topics that have been left out for science classes only will be solicited. Moreover, they will be balanced with other themes that leverage ecological understanding such as culture, spiritual, social and political aspects. The inclusion allows for the agreement of the diverse ideas and beliefs noted earlier.
  
  In a collaborative learning environment, the most important is the convergence of ideas and interests. Successful and sustainable school change, Fullan (Fullan,1997 as cited i
    
    
    
    
    One promising suggestion put forward by Selby and Clover about achieving ecological literacy is to transform schools into collaborative learning communities. A collaboration that reflects a vibrant living system that imitates the values and principles held intrinsically in natural ecosystems (Selby, 2000). Such a call is evident in the recent trends where schools are increasingly incorporating ecological themes and topics in curriculum development.

  A positive response or support is an opportunity to build a school philosophy in which environmental awareness and sensitivity are considered a priority. It is an important opportunity to give young learners, and maybe other community members who are stuck in unyielding worldviews, the chance to make the desired change. The key reason is that the collaboration will allow the integration of diverse ideas and consequently acknowledge beliefs and values held by diverse individuals.
  
  David Selby is one of the scholars who support collaborative learning or creating vibrant learning communities in schools (Selby, 2000). At this juncture, a learning community becomes more of a process than a place where academic knowledge is reinterpreted for a passing mark only. Reflecting on Mezirow’s steps of transformative learning, this process will grow systematically from “exploration of options for new roles, relationships, and actions to planning a course of action, acquiring knowledge and skills for implementing one’s plans” (Mezirow, 1999).
  
  Selby has joined Mezirow’s steps through what he calls strands. Insofar, the next strand is awakened by the achievement of the previous strand similar to Mezirow’s steps. Here, the process is clearly triggered by the new ethic in which aggressive, plundering human beings have abandoned their destructive ways, recognized their dependence on Planet Earth and attempted to live on more equal traction with the rest of nature (Selby, 2000). The chance to sustain the ecology lies in the fact that, people are presenting a deep and transformative, as in opposition to shallow and reformist ecological worldview within which the principal conjectures underlying the prevailing economic approach are nullified and changes identified.
  
  With the growing perception, it is important to develop collaborative learning with a bio-centric philosophy. The reason is that such a philosophy would embrace the idea of human versus nature in which relationship is characterized by events that are processes rather than the place where academic knowledge is reinterpreted for an economic point only. As such, environmental themes and topics that have been left out for science classes only will be solicited. Moreover, they will be balanced with other themes that leverage ecological understanding such as culture, spiritual, social and political aspects. The inclusion allows for the agreement of the diverse ideas and beliefs noted earlier.
  
  In a collaborative learning environment, the most important is the convergence of ideas and interests. Successful and sustainable school change, Fullan (Fullan,1997 as cited i
    
    
    One promising suggestion put forward by Selby and Clover about achieving ecological literacy is to transform schools into collaborative learning communities. A collaboration that reflects a vibrant living system that imitates the values and principles held intrinsically in natural ecosystems (Selby, 2000). Such a call is evident in the recent trends where schools are increasingly incorporating ecological themes and topics in curriculum development.

  A positive response or support is an opportunity to build a school philosophy in which environmental awareness and sensitivity are considered a priority. It is an important opportunity to give young learners, and maybe other community members who are stuck in unyielding worldviews, the chance to make the desired change. The key reason is that the collaboration will allow the integration of diverse ideas and consequently acknowledge beliefs and values held by diverse individuals.
  
  David Selby is one of the scholars who support collaborative learning or creating vibrant learning communities in schools (Selby, 2000). At this juncture, a learning community becomes more of a process than a place where academic knowledge is reinterpreted for a passing mark only. Reflecting on Mezirow’s steps of transformative learning, this process will grow systematically from “exploration of options for new roles, relationships, and actions to planning a course of action, acquiring knowledge and skills for implementing one’s plans” (Mezirow, 1999).
  
  Selby has joined Mezirow’s steps through what he calls strands. Insofar, the next strand is awakened by the achievement of the previous strand similar to Mezirow’s steps. Here, the process is clearly triggered by the new ethic in which aggressive, plundering human beings have abandoned their destructive ways, recognized their dependence on Planet Earth and attempted to live on more equal traction with the rest of nature (Selby, 2000). The chance to sustain the ecology lies in the fact that, people are presenting a deep and transformative, as in opposition to shallow and reformist ecological worldview within which the principal conjectures underlying the prevailing economic approach are nullified and changes identified.
  
  With the growing perception, it is important to develop collaborative learning with a bio-centric philosophy. The reason is that such a philosophy would embrace the idea of human versus nature in which relationship is characterized by events that are processes rather than the place where academic knowledge is reinterpreted for an economic point only. As such, environmental themes and topics that have been left out for science classes only will be solicited. Moreover, they will be balanced with other themes that leverage ecological understanding such as culture, spiritual, social and political aspects. The inclusion allows for the agreement of the diverse ideas and beliefs noted earlier.
  
  In a collaborative learning environment, the most important is the convergence of ideas and interests. Successful and sustainable school change, Fullan (Fullan,1997 as cited i
    
    One promising suggestion put forward by Selby and Clover about achieving ecological literacy is to transform schools into collaborative learning communities. A collaboration that reflects a vibrant living system that imitates the values and principles held intrinsically in natural ecosystems (Selby, 2000). Such a call is evident in the recent trends where schools are increasingly incorporating ecological themes and topics in curriculum development.

  A positive response or support is an opportunity to build a school philosophy in which environmental awareness and sensitivity are considered a priority. It is an important opportunity to give young learners, and maybe other community members who are stuck in unyielding worldviews, the chance to make the desired change. The key reason is that the collaboration will allow the integration of diverse ideas and consequently acknowledge beliefs and values held by diverse individuals.
  
  David Selby is one of the scholars who support collaborative learning or creating vibrant learning communities in schools (Selby, 2000). At this juncture, a learning community becomes more of a process than a place where academic knowledge is reinterpreted for a passing mark only. Reflecting on Mezirow’s steps of transformative learning, this process will grow systematically from “exploration of options for new roles, relationships, and actions to planning a course of action, acquiring knowledge and skills for implementing one’s plans” (Mezirow, 1999).
  
  Selby has joined Mezirow’s steps through what he calls strands. Insofar, the next strand is awakened by the achievement of the previous strand similar to Mezirow’s steps. Here, the process is clearly triggered by the new ethic in which aggressive, plundering human beings have abandoned their destructive ways, recognized their dependence on Planet Earth and attempted to live on more equal traction with the rest of nature (Selby, 2000). The chance to sustain the ecology lies in the fact that, people are presenting a deep and transformative, as in opposition to shallow and reformist ecological worldview within which the principal conjectures underlying the prevailing economic approach are nullified and changes identified.
  
  With the growing perception, it is important to develop collaborative learning with a bio-centric philosophy. The reason is that such a philosophy would embrace the idea of human versus nature in which relationship is characterized by events that are processes rather than the place where academic knowledge is reinterpreted for an economic point only. As such, environmental themes and topics that have been left out for science classes only will be solicited. Moreover, they will be balanced with other themes that leverage ecological understanding such as culture, spiritual, social and political aspects. The inclusion allows for the agreement of the diverse ideas and beliefs noted earlier.
  
  In a collaborative learning environment, the most important is the convergence of ideas and interests. Successful and sustainable school change, Fullan (Fullan,1997 as cited i
    One promising suggestion put forward by Selby and Clover about achieving ecological literacy is to transform schools into collaborative learning communities. A collaboration that reflects a vibrant living system that imitates the values and principles held intrinsically in natural ecosystems (Selby, 2000). Such a call is evident in the recent trends where schools are increasingly incorporating ecological themes and topics in curriculum development.

  A positive response or support is an opportunity to build a school philosophy in which environmental awareness and sensitivity are considered a priority. It is an important opportunity to give young learners, and maybe other community members who are stuck in unyielding worldviews, the chance to make the desired change. The key reason is that the collaboration will allow the integration of diverse ideas and consequently acknowledge beliefs and values held by diverse individuals.
  
  David Selby is one of the scholars who support collaborative learning or creating vibrant learning communities in schools (Selby, 2000). At this juncture, a learning community becomes more of a process than a place where academic knowledge is reinterpreted for a passing mark only. Reflecting on Mezirow’s steps of transformative learning, this process will grow systematically from “exploration of options for new roles, relationships, and actions to planning a course of action, acquiring knowledge and skills for implementing one’s plans” (Mezirow, 1999).
  
  Selby has joined Mezirow’s steps through what he calls strands. Insofar, the next strand is awakened by the achievement of the previous strand similar to Mezirow’s steps. Here, the process is clearly triggered by the new ethic in which aggressive, plundering human beings have abandoned their destructive ways, recognized their dependence on Planet Earth and attempted to live on more equal traction with the rest of nature (Selby, 2000). The chance to sustain the ecology lies in the fact that, people are presenting a deep and transformative, as in opposition to shallow and reformist ecological worldview within which the principal conjectures underlying the prevailing economic approach are nullified and changes identified.
  
  With the growing perception, it is important to develop collaborative learning with a bio-centric philosophy. The reason is that such a philosophy would embrace the idea of human versus nature in which relationship is characterized by events that are processes rather than the place where academic knowledge is reinterpreted for an economic point only. As such, environmental themes and topics that have been left out for science classes only will be solicited. Moreover, they will be balanced with other themes that leverage ecological understanding such as culture, spiritual, social and political aspects. The inclusion allows for the agreement of the diverse ideas and beliefs noted earlier.
  
  In a collaborative learning environment, the most important is the convergence of ideas and interests. Successful and sustainable school change, Fullan (Fullan,1997 as cited i
    
    One promising suggestion put forward by Selby and Clover about achieving ecological literacy is to transform schools into collaborative learning communities. A collaboration that reflects a vibrant living system that imitates the values and principles held intrinsically in natural ecosystems (Selby, 2000). Such a call is evident in the recent trends where schools are increasingly incorporating ecological themes and topics in curriculum development.

  A positive response or support is an opportunity to build a school philosophy in which environmental awareness and sensitivity are considered a priority. It is an important opportunity to give young learners, and maybe other community members who are stuck in unyielding worldviews, the chance to make the desired change. The key reason is that the collaboration will allow the integration of diverse ideas and consequently acknowledge beliefs and values held by diverse individuals.
  
  David Selby is one of the scholars who support collaborative learning or creating vibrant learning communities in schools (Selby, 2000). At this juncture, a learning community becomes more of a process than a place where academic knowledge is reinterpreted for a passing mark only. Reflecting on Mezirow’s steps of transformative learning, this process will grow systematically from “exploration of options for new roles, relationships, and actions to planning a course of action, acquiring knowledge and skills for implementing one’s plans” (Mezirow, 1999).
  
  Selby has joined Mezirow’s steps through what he calls strands. Insofar, the next strand is awakened by the achievement of the previous strand similar to Mezirow’s steps. Here, the process is clearly triggered by the new ethic in which aggressive, plundering human beings have abandoned their destructive ways, recognized their dependence on Planet Earth and attempted to live on more equal traction with the rest of nature (Selby, 2000). The chance to sustain the ecology lies in the fact that, people are presenting a deep and transformative, as in opposition to shallow and reformist ecological worldview within which the principal conjectures underlying the prevailing economic approach are nullified and changes identified.
  
  With the growing perception, it is important to develop collaborative learning with a bio-centric philosophy. The reason is that such a philosophy would embrace the idea of human versus nature in which relationship is characterized by events that are processes rather than the place where academic knowledge is reinterpreted for an economic point only. As such, environmental themes and topics that have been left out for science classes only will be solicited. Moreover, they will be balanced with other themes that leverage ecological understanding such as culture, spiritual, social and political aspects. The inclusion allows for the agreement of the diverse ideas and beliefs noted earlier.
  
  In a collaborative learning environment, the most important is the convergence of ideas and interests. Successful and sustainable school change, Fullan (Fullan,1997 as cited i
    
    
    One promising suggestion put forward by Selby and Clover about achieving ecological literacy is to transform schools into collaborative learning communities. A collaboration that reflects a vibrant living system that imitates the values and principles held intrinsically in natural ecosystems (Selby, 2000). Such a call is evident in the recent trends where schools are increasingly incorporating ecological themes and topics in curriculum development.

  A positive response or support is an opportunity to build a school philosophy in which environmental awareness and sensitivity are considered a priority. It is an important opportunity to give young learners, and maybe other community members who are stuck in unyielding worldviews, the chance to make the desired change. The key reason is that the collaboration will allow the integration of diverse ideas and consequently acknowledge beliefs and values held by diverse individuals.
  
  David Selby is one of the scholars who support collaborative learning or creating vibrant learning communities in schools (Selby, 2000). At this juncture, a learning community becomes more of a process than a place where academic knowledge is reinterpreted for a passing mark only. Reflecting on Mezirow’s steps of transformative learning, this process will grow systematically from “exploration of options for new roles, relationships, and actions to planning a course of action, acquiring knowledge and skills for implementing one’s plans” (Mezirow, 1999).
  
  Selby has joined Mezirow’s steps through what he calls strands. Insofar, the next strand is awakened by the achievement of the previous strand similar to Mezirow’s steps. Here, the process is clearly triggered by the new ethic in which aggressive, plundering human beings have abandoned their destructive ways, recognized their dependence on Planet Earth and attempted to live on more equal traction with the rest of nature (Selby, 2000). The chance to sustain the ecology lies in the fact that, people are presenting a deep and transformative, as in opposition to shallow and reformist ecological worldview within which the principal conjectures underlying the prevailing economic approach are nullified and changes identified.
  
  With the growing perception, it is important to develop collaborative learning with a bio-centric philosophy. The reason is that such a philosophy would embrace the idea of human versus nature in which relationship is characterized by events that are processes rather than the place where academic knowledge is reinterpreted for an economic point only. As such, environmental themes and topics that have been left out for science classes only will be solicited. Moreover, they will be balanced with other themes that leverage ecological understanding such as culture, spiritual, social and political aspects. The inclusion allows for the agreement of the diverse ideas and beliefs noted earlier.
  
  In a collaborative learning environment, the most important is the convergence of ideas and interests. Successful and sustainable school change, Fullan (Fullan,1997 as cited i
    One promising suggestion put forward by Selby and Clover about achieving ecological literacy is to transform schools into collaborative learning communities. A collaboration that reflects a vibrant living system that imitates the values and principles held intrinsically in natural ecosystems (Selby, 2000). Such a call is evident in the recent trends where schools are increasingly incorporating ecological themes and topics in curriculum development.

  A positive response or support is an opportunity to build a school philosophy in which environmental awareness and sensitivity are considered a priority. It is an important opportunity to give young learners, and maybe other community members who are stuck in unyielding worldviews, the chance to make the desired change. The key reason is that the collaboration will allow the integration of diverse ideas and consequently acknowledge beliefs and values held by diverse individuals.
  
  David Selby is one of the scholars who support collaborative learning or creating vibrant learning communities in schools (Selby, 2000). At this juncture, a learning community becomes more of a process than a place where academic knowledge is reinterpreted for a passing mark only. Reflecting on Mezirow’s steps of transformative learning, this process will grow systematically from “exploration of options for new roles, relationships, and actions to planning a course of action, acquiring knowledge and skills for implementing one’s plans” (Mezirow, 1999).
  
  Selby has joined Mezirow’s steps through what he calls strands. Insofar, the next strand is awakened by the achievement of the previous strand similar to Mezirow’s steps. Here, the process is clearly triggered by the new ethic in which aggressive, plundering human beings have abandoned their destructive ways, recognized their dependence on Planet Earth and attempted to live on more equal traction with the rest of nature (Selby, 2000). The chance to sustain the ecology lies in the fact that, people are presenting a deep and transformative, as in opposition to shallow and reformist ecological worldview within which the principal conjectures underlying the prevailing economic approach are nullified and changes identified.
  
  With the growing perception, it is important to develop collaborative learning with a bio-centric philosophy. The reason is that such a philosophy would embrace the idea of human versus nature in which relationship is characterized by events that are processes rather than the place where academic knowledge is reinterpreted for an economic point only. As such, environmental themes and topics that have been left out for science classes only will be solicited. Moreover, they will be balanced with other themes that leverage ecological understanding such as culture, spiritual, social and political aspects. The inclusion allows for the agreement of the diverse ideas and beliefs noted earlier.
  
  In a collaborative learning environment, the most important is the convergence of ideas and interests. Successful and sustainable school change, Fullan (Fullan,1997 as cited i
    
    One promising suggestion put forward by Selby and Clover about achieving ecological literacy is to transform schools into collaborative learning communities. A collaboration that reflects a vibrant living system that imitates the values and principles held intrinsically in natural ecosystems (Selby, 2000). Such a call is evident in the recent trends where schools are increasingly incorporating ecological themes and topics in curriculum development.

  A positive response or support is an opportunity to build a school philosophy in which environmental awareness and sensitivity are considered a priority. It is an important opportunity to give young learners, and maybe other community members who are stuck in unyielding worldviews, the chance to make the desired change. The key reason is that the collaboration will allow the integration of diverse ideas and consequently acknowledge beliefs and values held by diverse individuals.
  
  David Selby is one of the scholars who support collaborative learning or creating vibrant learning communities in schools (Selby, 2000). At this juncture, a learning community becomes more of a process than a place where academic knowledge is reinterpreted for a passing mark only. Reflecting on Mezirow’s steps of transformative learning, this process will grow systematically from “exploration of options for new roles, relationships, and actions to planning a course of action, acquiring knowledge and skills for implementing one’s plans” (Mezirow, 1999).
  
  Selby has joined Mezirow’s steps through what he calls strands. Insofar, the next strand is awakened by the achievement of the previous strand similar to Mezirow’s steps. Here, the process is clearly triggered by the new ethic in which aggressive, plundering human beings have abandoned their destructive ways, recognized their dependence on Planet Earth and attempted to live on more equal traction with the rest of nature (Selby, 2000). The chance to sustain the ecology lies in the fact that, people are presenting a deep and transformative, as in opposition to shallow and reformist ecological worldview within which the principal conjectures underlying the prevailing economic approach are nullified and changes identified.
  
  With the growing perception, it is important to develop collaborative learning with a bio-centric philosophy. The reason is that such a philosophy would embrace the idea of human versus nature in which relationship is characterized by events that are processes rather than the place where academic knowledge is reinterpreted for an economic point only. As such, environmental themes and topics that have been left out for science classes only will be solicited. Moreover, they will be balanced with other themes that leverage ecological understanding such as culture, spiritual, social and political aspects. The inclusion allows for the agreement of the diverse ideas and beliefs noted earlier.
  
  In a collaborative learning environment, the most important is the convergence of ideas and interests. Successful and sustainable school change, Fullan (Fullan,1997 as cited i`;

  

  res.status(200).json({ data })
}
