import Head from 'next/head'
import { useRef } from 'react'
import { useEffect } from 'react'
import styled from 'styled-components'
import Brand from '../shared/components/Brand/Brand'
import ConnectBoard from '../shared/components/ConnectBoard/ConnectBoard'
import Faq from '../shared/components/Faq/Faq'
import GoogleChart from '../shared/components/GoogleChart/GoogleChart'
import HoverBoard from '../shared/components/HoverBoard/HoverBoard'
import LandingPage from '../shared/components/LandingPage/LandingPage'
import Navbar from '../shared/components/Navbar/Navbar'
import Playground from '../shared/components/Playground/Playground'
import Playground2 from '../shared/components/Playground2/Playground2'
import { Projects } from '../shared/components/Projects/Projects'
import Testimonials from '../shared/components/Testimonials/Testimonials'


const getMain = () => {
  return (
    <main>
        <Navbar />
        <section id='landingpage'>
          <LandingPage />
        </section>
        <section id='hover'>
          {/* <HoverBoard /> */}
          <ConnectBoard />
        </section>
        <section id='playground'>
          {/* <Testimonials /> */}
          <Playground />
        </section>
        <section id='faq'>
          <Projects />
          {/* <Faq /> */}
        </section>
        
        {/* <Brand /> */}
        {/* <Playground2 /> */}

        {/* <GoogleChart /> */}
      </main>
  )
}

export default function Home() {

  return (
    <div>
      <Head>
        <title>Nextsy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" /> 
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {getMain()}
    </div>
  )
}
