import Head from 'next/head'
import { useRef } from 'react'
import { useEffect } from 'react'
import styled from 'styled-components'
import Brand from '../shared/components/Brand/Brand'
import Faq from '../shared/components/Faq/Faq'
import GoogleChart from '../shared/components/GoogleChart/GoogleChart'
import HoverBoard from '../shared/components/HoverBoard/HoverBoard'
import LandingPage from '../shared/components/LandingPage/LandingPage'
import Navbar from '../shared/components/Navbar/Navbar'
import Playground from '../shared/components/Playground/Playground'
import Playground2 from '../shared/components/Playground2/Playground2'


export default function Home() {

  return (
    <div>
      <Head>
        <title>Nextsy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" /> 
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <section id='landingpage'>
          <LandingPage />
        </section>
        <section id='hover'>
          <HoverBoard />
        </section>
        <section id='playground'>
          <Playground />
        </section>
        <section id='faq'>
          <Faq />
        </section>
        
        <Brand />
        <Playground2 />

        {/* <GoogleChart /> */}
      </main>
    </div>
  )
}
