import React from 'react'

import Head from 'next/head'
import { useRef } from 'react'
import { useEffect } from 'react'
import styled from 'styled-components'

const getMain = () => {
	return (
		<div>hello</div>
	)
}

export default function Home() {

  return (
    <div>
      <Head>
        <title>Nextsy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" /> 
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@500&family=Dancing+Script:wght@700&family=Rubik+Distressed&display=swap" rel="stylesheet" />
        
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {getMain()} 

    </div>
  )
}

