import React, { useState } from 'react'
import Head from 'next/head'
import { useRef } from 'react'
import { useEffect } from 'react'
import styled from 'styled-components'
import axios from 'axios'

const getMain = ({data}) => {
	return (
		<div>data</div>
	)
}
export default function Home() {
  const [data, setData] = useState(null)
  useEffect(() => {
    const options = {
      method: 'GET',
      url: 'https://deezerdevs-deezer.p.rapidapi.com/artist/16000',
      headers: {
        'X-RapidAPI-Key': '9519828400msh6fc8c24fd0ddefep17152fjsn33af84712d65',
        'X-RapidAPI-Host': 'deezerdevs-deezer.p.rapidapi.com'
      }
    };
    
    
    axios.request(options).then(function (response) {
      console.log(response.data)
      setData(response.data)
    }).catch(function (error) {
      console.error(error.response.data)
      setData(error.response.data)
    })
  }, []);


  return (
    <div>
      <Head>
        <title>Nextsy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" /> 
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@500&family=Dancing+Script:wght@700&family=Rubik+Distressed&display=swap" rel="stylesheet" />
        
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* {getMain(data)}  */}
      <div>
        <pre>
          <code>
          {JSON.stringify(data, null, 2)}
          </code>
        </pre> 
      </div>
           
    </div>
  )
}

